In [ ]:
Consider the below code to answer further questions:
import numpy as np
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_)
Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [2]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(list_)

print(type(list_))
print(type(array_list))



<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
Yes, there is a difference in the data type of variables list_ and array_list.
The variable list_ is a Python list object which can contain elements of any data type, whereas array_list is a numpy array
object which can only contain elements of the same data type.

In [ ]:
Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [3]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(list_)

# Print data type of each element in list_
for element in list_:
    print(type(element))

# Print data type of each element in array_list
for element in array_list:
    print(type(element))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [ ]:
Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)

In [4]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print("Data type of elements in list_:")
for elem in list_:
    print(type(elem))

print("Data type of elements in array_list:")
print(array_list.dtype)

Data type of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
Data type of elements in array_list:
<U1


In [ ]:
Yes, there will be a difference in the data type of the elements present in both the variables, list_ and array_list.
Before the change, array_list was created without specifying the data type, so NumPy automatically inferred the data type of 
the elements in list_ to be string. After the change, array_list is explicitly converted to integer data type using the dtype
parameter.


In [ ]:
Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [5]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 7 , 5 , 6 ] ]
num_array = np.array(object = num_list)
#print the shape of num_array
print(np.shape(num_array))
#print the size of num_array
print(np.size(num_array))

(2, 3)
6


In [ ]:
Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.

In [6]:
import numpy as np
data=np.zeros((3,3))
print(data)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
Q6. Create an identity matrix of shape (5,5) using numpy functions?

In [7]:
import numpy as np

identity_matrix = np.identity(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
